version: '3.8'

services:

  # global services (with port binding to host)

  fluent-bit:
    image: fluent/fluent-bit:1.8
    ports:
        - "24224:24224/tcp"
        - "8125:8125/udp"
    volumes:
        - ./config/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
        - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - fluent
    environment:
        ELASTIC_SEARCH_HOST: test-3363464309.us-east-1.bonsaisearch.net
        ELASTIC_SEARCH_USER: g2b6vkkbkg
        ELASTIC_SEARCH_PWD: en4lwyobng
        #ELASTIC_SEARCH_PWD: /run/secrets/secret_elastic_search_pwd
    # secrets:
    #   - secret_elastic_search_pwd


  # replica services (no port binding to host)

  logger-a:
      image: chentex/random-logger
      depends_on:
        - fluent-bit
      networks:
        - fluent
      logging:
        driver: fluentd
        options:
          fluentd-async: 'true'
          tag: logs

  logger-b:
      image: chentex/random-logger
      depends_on:
        - fluent-bit
      networks:
        - fluent
      logging:
        driver: fluentd
        options:
          fluentd-async: 'true'
          tag: logs

# secrets:

#    secret_elastic_search_pwd:
#     file: ./config/es/password.txt

networks:

  fluent:
    driver: bridge