version: '3.8'

services:
  # global services (with port binding to host)
  fluent-bit:
    image: fluent-beats:latest
    build: .
    ports:
        - "24224:24224/tcp"
        - "8125:8125/udp"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - fluent
    environment:
        ES_CLOUD_ID: /run/secrets/secret.service.ecs.cloud_id
        ES_CLOUD_AUTH: /run/secrets/secret.service.ecs.cloud_auth
    secrets:
      - source: secret.service.ecs.cloud_id.v1
        target: secret.service.ecs.cloud_id
      - source: secret.service.ecs.cloud_auth.v1
        target: secret.service.ecs.cloud_auth

  # replica services (no port binding to host)
  logger-a:
      image: chentex/random-logger
      depends_on:
        - fluent-bit
      networks:
        - fluent
      labels:
        flb_env: "prod"
        flb_service: "logger-a"
      logging:
        driver: fluentd
        options:
          #fluentd-async: 'true'
          labels-regex: "^flb_.*"
          tag: logs

  logger-b:
      image: chentex/random-logger
      depends_on:
        - fluent-bit
      networks:
        - fluent
      labels:
        flb_env: "prod"
        flb_service: "logger-b"

      logging:
        driver: fluentd
        options:
          #fluentd-async: 'true'
          labels-regex: "^flb_.*"
          tag: logs

secrets:
   secret.service.ecs.cloud_id.v1:
    file: ./config/es/cloud_id.txt
   secret.service.ecs.cloud_auth.v1:
    file: ./config/es/cloud_auth.txt

networks:
  fluent:
    driver: bridge