version: '3.8'

services:
  fluent-beats:
    image: fluent-beats/fluent-beats:latest
    build: .
    ports:
        - "24224:24224/tcp"
        - "8125:8125/udp"
    networks:
      - host
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /var/lib/docker/containers:/var/lib/docker/containers
    secrets:
      - source: secret.fluent-beats.es_http_host.v1
        target: es-host.txt
      - source: secret.fluent-beats.es_http_pwd.v1
        target: es-pwd.txt
    configs:
      - source: config.fluent-beats.env_file.v1
        target: /run/configs/fluent-beats.env

secrets:
   secret.fluent-beats.es_http_host.v1:
    external: true
   secret.fluent-beats.es_http_pwd.v1:
    external: true

configs:
  config.fluent-beats.env_file.v1:
    external: true

networks:
  host:
    name: host
    external: true