version: '3.8'

services:
  fluent-beats:
    image: fluent-beats/fluent-beats:latest
    build: .
    ports:
        - "2020:2020/tcp"
        - "24224:24224/tcp"
        - "8125:8125/udp"
    healthcheck:
      test: "wget --spider http://localhost:2020/api/v1/health || exit 1"
      interval: 60s
      start_period: 60s
    networks:
      - host
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /proc:/hostfs/proc:ro
    secrets:
      - source: secret.fluent-beats.es_http_host.v1
        target: es-host.txt
      - source: secret.fluent-beats.es_http_pwd.v1
        target: es-pwd.txt
    configs:
      - source: config.fluent-beats.env_file.v1
        target: /run/configs/fluent-beats.env
    deploy:
      resources:
          limits:
            cpus: '0.50'
            memory: 50M
          reservations:
            cpus: '0.25'
            memory: 15M
secrets:
   secret.fluent-beats.es_http_host.v1:
    external: true
   secret.fluent-beats.es_http_pwd.v1:
    external: true

configs:
  config.fluent-beats.env_file.v1:
    external: true

networks:
  host:
    name: host
    external: true