version: '3.8'

services:
  fluent-beats:
    image: fluent-beats/fluent-beats:latest
    build: .
    ports:
        - "24224:24224/tcp"
        - "8125:8125/udp"
    networks:
      - host
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /var/lib/docker/containers:/var/lib/docker/containers
    environment:
        ES_HTTP_HOST_SECRET: /run/secrets/secret.service.es.http_host
        ES_HTTP_PWD_SECRET: /run/secrets/secret.service.es.http_pwd
    secrets:
      - source: secret.service.es.http_host.v1
        target: secret.service.es.http_host
      - source: secret.service.es.http_pwd.v1
        target: secret.service.es.http_pwd

secrets:
   secret.service.es.http_host.v1:
    external: true
   secret.service.es.http_pwd.v1:
    external: true

networks:
  host:
    name: host
    external: true