name: Publish

on:
  release:
    types: [created]

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Image Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name=${{ env.DOCKER_REGISTRY }}/${{ github.repository }}
          tags: |
            type=sha,format=long,prefix=

      - name: Registry Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download plugins
        run: |
            chmod +x ./github/download_plugins.sh
            ./github/download_plugins.sh
        shell: bash

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./code
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}